# -*- coding: utf-8 -*-
SpiderConf=dict(
    AC=dict(
        alias_name="格雷沙姆学院",
        alias_en="Gresham College",
        base_url="www.gresham.ac.uk",
        start_urls=[
            'https://www.gresham.ac.uk/watch/?files=audio',
            'https://www.gresham.ac.uk/watch/?files=video',
            'https://www.gresham.ac.uk/watch/?files=transcript'
        ],
        type="multiple",
        params=[
            "storeConf","limit_count","trash_data"
        ]
    ),
    BC=dict(
        alias_name="波士顿大学",
        alias_en="Boston College",
        base_url="bc.edu",
        start_urls=[
            'http://frontrow.bc.edu/programs/default.php?page=1&category=all',
        ],
        type="multiple",
        params=[
            "storeConf","limit_count","trash_data"
        ]
    ),
    CMU=dict(
        alias_name="卡内基梅隆学院",
        alias_en="Carnegie Mellon College",
        base_url="cmu.edu",
        start_urls=[
            'http://oli.cmu.edu/learn-with-oli/see-our-free-open-courses/',
        ],
        type="single",
        params=[
            "storeConf","limit_count","trash_data"
        ]
    ),
    DUKE=dict(
        alias_name="杜克大学",
        alias_en="Duke University",
        base_url="duke.edu",
        start_urls=[
            'https://law.duke.edu/cspd/lectures/',
        ],
        type="single",
        params=[
            "storeConf","limit_count","trash_data"
        ]
    ),
    EDX=dict(
        alias_name="EDX在线学习平台",
        alias_en="EDX",
        base_url="edx.org",
        start_urls=[
            'https://www.edx.org/api/v1/catalog/search?page=1&page_size=10&partner=edx&content_type[]=courserun&content_type[]=program&featured_course_ids=course-v1%3APennX+SD1x+2T2017%2Ccourse-v1%3AUQx+IELTSx+3T2016%2Ccourse-v1%3AMicrosoft+DAT101x+2T2017%2Ccourse-v1%3AUCSanDiegoX+CSE165x+2T2017%2Ccourse-v1%3AGTx+CS1301x+1T2017%2Ccourse-v1%3AMicrosoft+DAT201x+2T2017&featured_programs_uuids=865bbad4-6643-4d59-85d3-936cf3a7acf4%2Cf5448140-88fc-451c-82cf-976504bdfa8d%2C482dee71-e4b9-4b42-a47b-3e16bb69e8f2%2C98b7344e-cd44-4a99-9542-09dfdb11d31b%2Ca015ce08-a727-46c8-92d1-679b23338bc1%2C77d865f3-456a-4ea6-9e0d-65529e8864d6',
        ],
        type="multiple",
        params=[
            "storeConf","limit_count","trash_data"
        ]
    ),
    HMS=dict(
        alias_name="哈佛大学",
        alias_en="Harvard University",
        base_url="harvard.edu",
        start_urls=[
            'http://mycourses.med.harvard.edu/ocw_rbview.asp',
        ],
        type="multiple",
        params=[
            "storeConf","limit_count","trash_data"
        ]
    ),
    JHSPH=dict(
        alias_name="约翰霍普金斯大学彭博公共卫生学院",
        alias_en="Johns Hopkins Bloomberg School of Public Health",
        base_url="jhsph.edu",
        start_urls=[
            'http://ocw.jhsph.edu/index.cfm/go/find.browse#courses',
        ],
        type="single",
        params=[
            "storeConf","limit_count","trash_data"
        ]
    ),
    MIT=dict(
        alias_name="麻省理工学院",
        alias_en="Massachusetts Institute of Technology",
        base_url="mit.edu",
        start_urls=[
            'https://ocw.mit.edu/courses/?utm_source=ocw-megamenu&utm_medium=link&utm_campaign=mclstudy#aeronautics-and-astronautics',
        ],
        type="single",
        params=[
            "storeConf","limit_count","trash_data"
        ]
    ),
    NewSu=dict(
        alias_name="波恩新闻大学",
        alias_en="Poynter's News University",
        base_url="newsu.org",
        start_urls=[
            'http://www.newsu.org/courses/all#table',
        ],
        type="multiple",
        params=[
            "storeConf","limit_count","trash_data"
        ]
    ),
    Nottingham=dict(
        alias_name="诺丁汉大学",
        alias_en="University of Nottingham",
        base_url="rdmc.nottingham.ac.uk",
        start_urls=[
            'https://rdmc.nottingham.ac.uk/browse?type=title',
        ],
        type="multiple",
        params=[
            "storeConf","limit_count","trash_data"
        ]
    ),
    OpenLearn=dict(
        alias_name="开放学习网",
        alias_en="The Open University",
        base_url="open.edu",
        start_urls=[
            'http://www.open.edu/openlearn/free-courses/full-catalogue',
        ],
        type="multiple",
        params=[
            "storeConf","limit_count","trash_data"
        ]
    ),
    OX=dict(
        alias_name="牛津大学",
        alias_en="University of Oxford",
        base_url="ox.ac.uk",
        start_urls=[
            'http://ota.ox.ac.uk/catalogue/index.html',
        ],
        type="single",
        params=[
            "storeConf","limit_count","trash_data"
        ]
    ),
    PCE_UW=dict(
        alias_name="华盛顿大学",
        alias_en="Professional & Continuing Education University of Washington",
        base_url="pce.uw.edu",
        start_urls=[
            'https://www.pce.uw.edu/program-finder?pagesize=12&page=1&onlyvalidsec=true&ajax=true',
        ],
        type="multiple",
        params=[
            "storeConf","limit_count","trash_data"
        ]
    ),
    Tudelft=dict(
        alias_name="代尔夫特理工大学",
        alias_en="Technische Universiteit Delft",
        base_url="tudelft.nl",
        start_urls=[
            'https://ocw.tudelft.nl/programs/',
        ],
        type="single",
        params=[
            "storeConf","limit_count","trash_data"
        ]
    ),
    TUFTS=dict(
        alias_name="塔夫茨大学",
        alias_en="Tufts University",
        base_url="tudelft.nl",
        start_urls=[
            'http://ocw.tufts.edu/CourseList',
        ],
        type="multiple",
        params=[
            "storeConf","limit_count","trash_data"
        ]
    ),
    UCI=dict(
        alias_name="加利福尼亚大学",
        alias_en="University of California, Irvine",
        base_url="ocw.uci.edu",
        start_urls=[
            'https://ocw.uci.edu/courses',
        ],
        type="single",
        params=[
            "storeConf","limit_count","trash_data"
        ]
    ),
    UMB=dict(
        alias_name="马萨诸塞州波士顿大学",
        alias_en="University of Massachusetts Boston",
        base_url="ocw.umb.edu",
        start_urls=[
            'http://ocw.umb.edu/courselist/index.html',
        ],
        type="multiple",
        params=[
            "storeConf","limit_count","trash_data"
        ]
    ),
    UMICH=dict(
        alias_name="密歇根大学",
        alias_en="University of Michigan",
        base_url="umich.edu",
        start_urls=[
            'https://open.umich.edu/find/find-open-educational-resources',
        ],
        type="multiple",
        params=[
            "storeConf","limit_count","trash_data"
        ]
    ),
    USU=dict(
        alias_name="犹他州立大学",
        alias_en="Utah State University",
        base_url="usu.edu",
        start_urls=[
            'http://ocw.usu.edu/courselist/index.html',
        ],
        type="single",
        params=[
            "storeConf","limit_count","trash_data"
        ]
    ),
    VTC=dict(
        alias_name="VTC计算机技术学习",
        alias_en="Virtual Training Company",
        base_url="vtc.com",
        start_urls=[
            'https://www.vtc.com/modules/products/titleList.php?mode=all&type=&searchStr=&page=1',
        ],
        type="multiple",
        params=[
            "storeConf","limit_count","trash_data"
        ]
    ),
    Yale=dict(
        alias_name="耶鲁大学",
        alias_en="Yale University",
        base_url="yale.com",
        start_urls=[
            'http://oyc.yale.edu/courses',
        ],
        type="multiple",
        params=[
            "storeConf","limit_count","trash_data"
        ]
    ),
    WangYi=dict(
        alias_name="网易163新闻",
        alias_en="163",
        base_url="news.163.com",
        start_urls=[
            'http://www.163.com/'
        ],
        type="multiple",
        params=[
            "storeConf","limit_count","trash_data"
        ]
    ),
)